### ISSUE TITLE
OpenApi generator

### ISSUE THREAD

**Issue by use-to** [helpwave/web#10]

**Comment by MaxSchaefer** [comment]
With b02c98a1541dbc92c82433f2de4b6307e6a13732 we got an interesting api wrapper. In my opinion this issue should be low priority.

**Comment by use-to** [comment]
@MaxSchaefer you assigned this to yourself? Whats the it progress status?

**Comment by MaxSchaefer** [comment]
No progress yet, low priority because of our existing api wrapper.

**Comment by JannikWibker** [comment]
I'll maybe implement this myself and add it as a npm script
