### ISSUE TITLE
Re-Design of Navbar

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#1001]
### Describe the feature

![Image](https://github.com/helpwave/web/assets/40192999/ef062b30-8c3e-4b56-a918-c550ea5031b8)

Our new navbar includes our logo and navitems. Until further discussed, we will keep the mobile menu for now. The hover menu could be an extended version of the "active" navitem @jonas-ester ? 

### Why is this feature needed?

fancy new landing-page

**Comment by DasProffi** [comment]
Done in #1003
