### ISSUE TITLE
Tasks product page - Tasks header section

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#1006]
![Section 1 (1)](https://github.com/helpwave/web/assets/40192999/5ed533d8-fac3-453e-8747-e35b4696b2f9)

**Comment by DasProffi** [comment]
@MaxSchaefer We are using an image for the tasks UI part of this section, correct? Or are we using the actual components of tasks?

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer We are using an image for the tasks UI part of this section, correct? Or are we using the actual components of tasks?

Images for now
