### ISSUE TITLE
Ward overview

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#105]
```[tasklist]
### Ward overview
- [ ] #104 
```

![Tasks - overview of wards in an organization-2](https://user-images.githubusercontent.com/40192999/230719510-8022aff9-69eb-4bbb-aaa2-8b15f577a290.jpg)

**Comment by DasProffi** [comment]
Is this still not ready? @MaxSchaefer
The design exists in Figma

**Comment by MaxSchaefer** [comment]
@DasProffi you are totally right! _Updated_
