### ISSUE TITLE
Visually compressed images on mobile

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#1051]
Open our landing page integration branch and check out the `/products/tasks` page. 
![IMG_13E1D5DA21AD-1](https://github.com/helpwave/web/assets/40192999/e8093178-ee73-48f0-b053-93ce9bcb8c40)

**Comment by DasProffi** [comment]
Should be fixed with #1042

**Comment by DasProffi** [comment]
Similar to #1063
