### ISSUE TITLE
Integrate CRUD endpoints properties

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#1054]
### Describe the feature

CRUD endpoints for managing properties are now available in services and ready to be integrated. 

### Why is this feature needed?

_Integration_

### Additional context

- GetPropertiesBySubjectTypeRequest
- GetPropertyRequest
- CreatePropertyRequest
- UpdatePropertyRequest

**Comment by DasProffi** [comment]
Done in #1083
