### ISSUE TITLE
TaskDetail view

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#137]
It should be possible to pass a task to this component. This component will be used in the future either to create or to update a task.

```[tasklist]
### TasksDetail view
- [ ] #135 
- [ ] #136 
```

![Group 45](https://user-images.githubusercontent.com/40192999/228654539-66bd1fa3-b919-4005-be0b-a15eb7e1ad0e.jpg)

**Comment by DasProffi** [comment]
not ready until #135 is closed

**Comment by use-to** [comment]
Should we mark this as `ready` because the most of it seems ready to me?

**Comment by DasProffi** [comment]
> Should we mark this as `ready` because the most of it seems ready to me?

But it can't be completed until the select exists, therefore I would argue it isn't ready. But maybe we should denote the meaning of the labels somewhere

**Comment by use-to** [comment]
> > Should we mark this as `ready` because the most of it seems ready to me?
> 
> But it can't be completed until the select exists, therefore I would argue it isn't ready. But maybe we should denote the meaning of the labels somewhere

True, but depending issues will be expressed differently. Not-ready really means not well defined issue.

**Comment by MaxSchaefer** [comment]
@use-to @DasProffi ready / Todo! We should display the assignable / not assignable state via the Project Status Backlog or Todo. I've also opened an [issue](https://github.com/helpwave/helpwave/issues/35) to synchronize or labels, its quite a colorful mess.

**Comment by use-to** [comment]
> @use-to @DasProffi ready / Todo! We should display the assignable / not assignable state via the Project Status Backlog or Todo. I've also opened an [issue](https://github.com/helpwave/helpwave/issues/35) to synchronize or labels, its quite a colorful mess.
> 

Okay, nice one! Didn't know about the synchronization. Good idea 💡
