### ISSUE TITLE
Rooms listing component

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#138]
![Rooms Section](https://user-images.githubusercontent.com/40192999/228655544-24f553fd-8641-4b37-874f-52e5616b151f.jpg)

**Comment by MaxSchaefer** [comment]
@JannikWibker should the entries really be draggable?

**Comment by JannikWibker** [comment]
@MaxSchaefer  yes, reorderable via dragging
when dragged the entries should only move in the y-direction and be have a box shadow clearly distinguishing the item being dragged from the rest.
one "design inspiration" which does something similar is google keep.

**Comment by DasProffi** [comment]
> @MaxSchaefer yes, reorderable via dragging when dragged the entries should only move in the y-direction and be have a box shadow clearly distinguishing the item being dragged from the rest. one "design inspiration" which does something similar is google keep.

How do we intend to allow dragging entries across pages?

**Comment by DasProffi** [comment]
Are the number inputs the default ones, or should we make another component out of it? @JannikWibker
