### ISSUE TITLE
Restructure the component folder

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#142]
The components folder in the tasks app has begun to grow quite much, we should implement a better way to organize the components as finding a specific one is becoming hard.

**Comment by DasProffi** [comment]
Any suggestions @JannikWibker @MaxSchaefer

**Comment by JannikWibker** [comment]
Add subfolders for a few categories of components:
- Layout / larger components
- Pills
- Tiles maybe?

**Comment by DasProffi** [comment]
Makes sense, right now we have different names for Tiles/Cards we should pick one

**Comment by MaxSchaefer** [comment]
> Makes sense, right now we have different names for Tiles/Cards we should pick one

Card
