### ISSUE TITLE
Switch to standardized logo

### ISSUE THREAD

**Issue by use-to** [helpwave/web#158]
Use [this icon](https://github.com/helpwave/helpwave/blob/main/assets/logo/logo.svg) instead of [this](https://github.com/helpwave/helpwave/blob/main/assets/logo/logo_circle.svg).

**Comment by DasProffi** [comment]
The new Icon should have a colored background, otherwise it could be not visible on a dark one

**Comment by use-to** [comment]
You can add a white background. https://github.com/helpwave/helpwave/issues/32

**Comment by DasProffi** [comment]
> You can add a white background. [helpwave/helpwave#32](https://github.com/helpwave/helpwave/issues/32)

Only needs approval: https://github.com/helpwave/helpwave/pull/33
