### ISSUE TITLE
Replace edit with edit icon

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#174]
We shoud replace the edit text for editing Ward and Organisation with a edit icon

**Comment by florian-sabonchi** [comment]
a list of our conventions can found here 

https://www.linkedin.com/in/rajarshisamaddar/?original_referer=https%3A%2F%2Fgithub.com%2F

@rajarshisamaddar

**Comment by rajarshisamaddar** [comment]
@florian-sabonchi assign me this issue I will start working on this ASAP

**Comment by rajarshisamaddar** [comment]
> a list of our conventions can found here
> 
> https://www.linkedin.com/in/rajarshisamaddar/?original_referer=https%3A%2F%2Fgithub.com%2F
> 
> @rajarshisamaddar

sorry, what is this link?

**Comment by florian-sabonchi** [comment]
> > a list of our conventions can found here
> > https://www.linkedin.com/in/rajarshisamaddar/?original_referer=https%3A%2F%2Fgithub.com%2F
> > @rajarshisamaddar
> 
> sorry, what is this link?

Sorry, my Misstake. Updated the link.
