### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by use-to** [helpwave/web#187]
Obviously we need to introduce some new components:
- [x] FeatureBlock
- [x] #254 
- [x] TwoColumnLayout (#167 + icon: 5% top)

**Comment by use-to** [comment]
![image](https://user-images.githubusercontent.com/13922835/233781993-7f205954-c56e-40f7-a939-a1a0965a5e26.png)

**Comment by use-to** [comment]
Unassinged @jonas-ester as designer, feel free to still work on this as a developer (just reassign yourself).

**Comment by DasProffi** [comment]
What is meant by "+ icon: 5% top"?

**Comment by use-to** [comment]
> What is meant by "+ icon: 5% top"?

The little arrow icon laying on the divider line 5% screen height distant from top (toolbar).
