### ISSUE TITLE
Fix Mobile Interceptor

### ISSUE THREAD

**Issue by use-to** [helpwave/web#193]
- [ ] fix font family (it's currently unset)
- [ ] serve mobile interception view on devices/windows with `width < 1350px` using media queries.

**Comment by DasProffi** [comment]
What is with non-mobile devices with a width of less than 1350px they won't be supported at all or can the mobile interceptor be clicked away like a dialog? @use-to

**Comment by use-to** [comment]
> What is with non-mobile devices with a width of less than 1350px they won't be supported at all or can the mobile interceptor be clicked away like a dialog? @use-to
> 
> Or is this just temporary?

Yes. Currently unsupported. We can try to improve our design supporting smaller devices. But for now it should be fine.

**Comment by florian-sabonchi** [comment]
> * [ ]  fix font family (it's currently unset)
> * [ ]  serve mobile interception view on devices/windows with `width < 1350px` using media queries.

Which font family should we use?
