### ISSUE TITLE
Basic landing page

### ISSUE THREAD

**Issue by JannikWibker** [helpwave/web#20]
- Informations about the project
- Basic informations about the Team?
- Contact infos -> HubSpot Form?
- Images? Mocks?

**Comment by JannikWibker** [comment]
In the future we should move this to its own sub-project (I'd suggest something like `/landing-page`), but this will have to wait until we better figure out deployment. For now this should just be a page in the dashboard (`/app` for now); most likely the index page.

**Comment by MaxSchaefer** [comment]
Let's use #27 as our tracking issue and close this one.
