### ISSUE TITLE
Issue loding website on mobile 

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#203]
Loading the websites in the mobile view with the help of the devtools leads to the following error: 

![image](https://user-images.githubusercontent.com/54689374/232251158-fbd82e61-f44d-4f7b-9788-f612e77d41ca.png)

**Comment by DasProffi** [comment]
Helpul: https://nextjs.org/docs/messages/react-hydration-error

**Comment by shivadharmi** [comment]
Hey, @florian-sabonchi and @use-to Can I pick this?

**Comment by MaxSchaefer** [comment]
@shivadharmi of course.

**Comment by shivadharmi** [comment]
Hello @MaxSchaefer. When running the project in my local and visiting the localhost url it is redirecting me to [https://staging-tasks.helpwave.de/auth/callback?fake_token=eyJzdWIiOiIxODE1OTcxMy01ZDRlLT[…]NDc5ODQiLCJlbWFpbCI6InRlc3RpbmUudGVzdEBoZWxwd2F2ZS5kZSJ9](https://staging-tasks.helpwave.de/auth/callback?fake_token=eyJzdWIiOiIxODE1OTcxMy01ZDRlLTRhZDUtOTRhZC1mYmI2YmIxNDc5ODQiLCJlbWFpbCI6InRlc3RpbmUudGVzdEBoZWxwd2F2ZS5kZSJ9)
Am I missing anything?

**Comment by MaxSchaefer** [comment]
> Hello @MaxSchaefer. When running the project in my local and visiting the localhost url it is redirecting me to [https://staging-tasks.helpwave.de/auth/callback?fake_token=eyJzdWIiOiIxODE1OTcxMy01ZDRlLT[…]NDc5ODQiLCJlbWFpbCI6InRlc3RpbmUudGVzdEBoZWxwd2F2ZS5kZSJ9](https://staging-tasks.helpwave.de/auth/callback?fake_token=eyJzdWIiOiIxODE1OTcxMy01ZDRlLTRhZDUtOTRhZC1mYmI2YmIxNDc5ODQiLCJlbWFpbCI6InRlc3RpbmUudGVzdEBoZWxwd2F2ZS5kZSJ9)
> Am I missing anything?

You can set the environment variable (`/tasks/.env`) `NEXT_PUBLIC_OAUTH_REDIRECT_URI` to `http://localhost:3000/auth/callback`.

**Comment by shivadharmi** [comment]
> http://localhost:3000/auth/callback

Got it @MaxSchaefer. Thank you!

**Comment by shivadharmi** [comment]
Hey @MaxSchaefer and @florian-sabonchi. I did some research on this. I found out that we are using the react-device-detect library to detect the device type which is causing this issue as it is using another library called ua-parser-js which is using window object to detect device type. But, here the problem is window object is not available during pre-rendering and it will available during the first render due to this react sees different dom trees and through the hydration error. We should be using the libraries that use media queries to detect the device size but, still, we can use the react-device-detect to know the device type (Android or IOS).

**Comment by shivadharmi** [comment]
> This library uses a technique called [user agent sniffing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent) to detect device information. That means it works by examining the [User Agent string](https://en.wikipedia.org/wiki/User_agent) given by a browser and comparing it to a list of browser and device names it knows about. This technique works, but [has drawbacks](https://css-tricks.com/browser-detection-is-bad/) and may or may not be the right approach, depending on what you're trying to achieve. If you need to detect a specific browser type (e.g. Chrome, Safari, Internet Explorer) or specific category of device (e.g. all iPods), this library can do that. If you just want your React app to behave differently or look different on mobiles in general, [CSS @media queries](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) and [matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) are probably what you want. There are many libraries that can help with using @media queries and matchMedia in React projects, such as [react-responsive](https://www.npmjs.com/package/react-responsive) and [@react-hook/media-query](https://www.npmjs.com/package/@react-hook/media-query).

This was part of react-device-detect readme. Please take a look and let me know if this makes sense then we need to think of other alternatives. And I can more detailed info if this doesn't make sense.

**Comment by DasProffi** [comment]
> @shivadharmi we can also try to move the platform detection to the [server side in Next.js](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props).
> 
> Maybe @DasProffi can give some insights about react-device-detect library.

I just used the library, because it manages the detection, we can also switch to another one, but the hydration error also occurred before using the package, so it's most likely not (the only) reason

**Comment by use-to** [comment]
#193

**Comment by shivadharmi** [comment]
> I just used the library, because it manages the detection, we can also switch to another one, but the hydration error also occurred before using the package, so it's most likely not (the only) reason

Hey, @DasProffi let me check on this.
