### ISSUE TITLE
Adopt react library for lucide svg icons

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#205]
Replace all SVGs with the ones of the library.

https://lucide.dev/docs/lucide-react

**Comment by MaxSchaefer** [comment]
@JannikWibker

**Comment by rajarshisamaddar** [comment]
> @rajarshisamaddar thanks for adding `lucide-react`'s library to the repository. This issue seams like a nice follow-up task. What do you think?

Yeah I think we should replace those SVG, I can work on this

**Comment by florian-sabonchi** [comment]
#244
