### ISSUE TITLE
SimpleBarReact for textare-component

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#209]
we shoud use the SimpleBarReact for the textarea-component

**Comment by florian-sabonchi** [comment]
Seems like that there is an knwown limitation https://github.com/Grsmto/simplebar/issues/333 instead of scrolling content the whole component is scrolled

**Comment by florian-sabonchi** [comment]
So i would suggest to set a maximum limit for Conten so that there is no need for scrolling

**Comment by MaxSchaefer** [comment]
@florian-sabonchi introducing a limit is not an option right now. Either we find a way to adopt SimpleBarReact to our needs or we should close this issue.
