### ISSUE TITLE
Component for time Strings

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#230]
- Dates and times should be mapped to a helpwave specific string for his create a new component
- Apply it to the TaskDetailView Components create date and the due date select

**Comment by MaxSchaefer** [comment]
@DasProffi what problem should this issue solve?

**Comment by DasProffi** [comment]
> @DasProffi what problem should this issue solve?

Currently, we have no clear time format, this component and issue should fix this. In the mocks you can see something like "13:00 - today", which can't be done by normal formatting therefore we should introduce a component to do this
