### ISSUE TITLE
Feedback button

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#233]
We need a button in `helpwave tasks` to gather feedback from the current user that is using the app.
The feedback button should open a new modal where we can collect arbitrary text from the user.

Design: https://github.com/helpwave/design/issues/3

**Comment by use-to** [comment]
Maybe we could connect a feedback form with #187

**Comment by MaxSchaefer** [comment]
> Maybe we could connect a feedback form with #187

Yes, good idea. The feedback modal can be in an already-opened state on the dashboard.

**Comment by MaxSchaefer** [comment]
In favor of #624
