### ISSUE TITLE
Replace green confirm button for deletion with red

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#245]
![image](https://user-images.githubusercontent.com/54689374/233423435-cad3fc9a-c232-43f7-9b3d-36ffc10c3d5e.png)

**Comment by shivadharmi** [comment]
Hey, @florian-sabonchi I would like to work on this issue. Can I go for it?

**Comment by florian-sabonchi** [comment]
Yes of course

**Comment by florian-sabonchi** [comment]
@shivadharmi you can work on it a list of our code convetions can be found here https://github.com/helpwave/helpwave/blob/main/development/CONVENTIONS.md

**Comment by shivadharmi** [comment]
Thank you @florian-sabonchi.

**Comment by shivadharmi** [comment]
Hi @florian-sabonchi. I have gone through the contribution documentation. I did the project setup in my local. I might need credentials to log in. Can you help me with this?

**Comment by florian-sabonchi** [comment]
> Hi @florian-sabonchi. I have gone through the contribution documentation. I did the project setup in my local. I might need credentials to log in. Can you help me with this?

Hi, thanks for your message  there is no login you can skip this step by entering empty username and password

**Comment by shivadharmi** [comment]
Hey @florian-sabonchi . As I can see from the code we are using a confirmation dialogue component.
There can be three types of actions:
- `Sucess`
- `Warning` 
- `Danger`
Shouldn't we consider three of them and design the confirmation dialogue in such a way that we can use it in all three scenarios? Where we will show red for negative actions, green for positive, and yellow for neutral.

**Comment by florian-sabonchi** [comment]
Yes, i agree sounds food to me

**Comment by shivadharmi** [comment]
okay @florian-sabonchi. I will work on it. Thanks!

**Comment by use-to** [comment]
> Hey @florian-sabonchi . As I can see from the code we are using a confirmation dialogue component. There can be three types of actions:
> 
> * `Sucess`
> * `Warning`
> * `Danger`
>   Shouldn't we consider three of them and design the confirmation dialogue in such a way that we can use it in all three scenarios? Where we will show the button in red color for negative actions, green color for positive, and yellow color for neutral.

Hey @shivadharmi, welcome!
Feel free taking a look at our design definitions (we got some colors there too):
https://www.figma.com/file/vCeohZgfJzkN4VQreBvAM0/helpwave-team-library?node-id=0%3A1&t=KXHkZ1jWg1mm3N0K-1
We received your mail and currently processing it!
Also checkout our development documentation and conventions: https://github.com/helpwave/helpwave/tree/main/development

**Comment by shivadharmi** [comment]
Hey @use-to, Thank you so much. I have gone through the doc. I will look into Figma and work accordingly.
