### ISSUE TITLE
Remove other/s from organization card

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#246]
![image](https://user-images.githubusercontent.com/54689374/233423595-c8dfb1af-1556-4989-9aab-bfafd95360de.png)

**Comment by florian-sabonchi** [comment]
could be a good issue for you @rajarshisamaddar

**Comment by rajarshisamaddar** [comment]
> could be a good issue for you @rajarshisamaddar

what do you mean by others?

**Comment by florian-sabonchi** [comment]
> > could be a good issue for you @rajarshisamaddar
> 
> what do you mean by others?

![image](https://user-images.githubusercontent.com/54689374/233431977-30701bdd-55f0-4986-994f-f3f7aa6b98f1.png)
instead of others here i would suggest to only show the number

**Comment by rajarshisamaddar** [comment]
> > > could be a good issue for you @rajarshisamaddar
> > 
> > what do you mean by others?
> 
> ![image](https://user-images.githubusercontent.com/54689374/233431977-30701bdd-55f0-4986-994f-f3f7aa6b98f1.png)
> instead of others here i would suggest to only show the number

Ok assign me this issue I'll fix it

**Comment by rajarshisamaddar** [comment]
@florian-sabonchi I'm working on this issue but having some problem the dev server is always redirecting to [URL](https://staging-tasks.helpwave.de/auth/callback?fake_token=eyJzdWIiOiIxODE1OTcxMy01ZDRlLTRhZDUtOTRhZC1mYmI2YmIxNDc5ODQiLCJlbWFpbCI6InRlc3RpbmUudGVzdEBoZWxwd2F2ZS5kZSJ9).

**Comment by use-to** [comment]
Make sure to keep your feature branch up to date with `main` (just merge it into your branch).
It's our new auth implemented by @MaxSchaefer 
For more advanced questions the best thing to do would be to ask him.

**Comment by MaxSchaefer** [comment]
@rajarshisamaddar take a look at https://github.com/helpwave/web/issues/288#issue-1681861231.
> You can set the environment variable (/tasks/.env) NEXT_PUBLIC_OAUTH_REDIRECT_URI to http://localhost:3000/auth/callback.

**Comment by use-to** [comment]
> @rajarshisamaddar take a look at https://github.com/helpwave/web/issues/288#issue-1681861231.
> > You can set the environment variable (/tasks/.env) NEXT_PUBLIC_OAUTH_REDIRECT_URI to http://localhost:3000/auth/callback.

I saw this addition in #289

**Comment by rajarshisamaddar** [comment]
@MaxSchaefer @use-to @florian-sabonchi  PR is created regarding this issue.
