### ISSUE TITLE
Add component documentation

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#248]
Every component should at least have 1 sentence describing its function and usage

**Comment by use-to** [comment]
@JannikWibker showed us a component library viewer some month ago. Maybe he could contribute here...

**Comment by MaxSchaefer** [comment]
> @JannikWibker showed us a component library viewer some month ago. Maybe he could contribute here...

Something like https://storybook.js.org

**Comment by shivadharmi** [comment]
Hey @MaxSchaefer, @use-to, and @DasProffi I can configure the storybook for the project. Should I pick this?
