### ISSUE TITLE
Landing page v1

### ISSUE THREAD

**Issue by use-to** [helpwave/web#27]
- [x] #31 
- [x] #32 
- [x] #33 
- [x] #37 
- [x] #53

**Comment by MaxSchaefer** [comment]
Upcoming issues for v2
- [ ] #36

**Comment by JannikWibker** [comment]
These are some of the things not implemented / addressed in the initial team page PR, I'll just leave them here for reference:

- dotted gradients
- migrate to twind? this is a general pain point of mine
- colors are all over the place (firstly from a design perspective -> should use more consistent ones maybe or standardize the ones currently in use and secondly from a code structure perspective -> use the tailwind config more)

**Comment by JannikWibker** [comment]
As this is marked as v1 and some things have been labelled as v2 can we close this?
