### ISSUE TITLE
twocolumn different sizes

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#275]
allow for different sizes in the twocolumn layout `"leftMaximized" | "normal" | "smallSidebar" `

smallSiderbar should be 70/30

**Comment by use-to** [comment]
Do you mean `smallSidebar`?

**Comment by use-to** [comment]
Also is it possible to make it entirely flexible so you can just give the ratios?

**Comment by MaxSchaefer** [comment]
A potential solution is to be fully flexible by replacing the vertical separator bar with something like a slider.
