### ISSUE TITLE
Room name should be limited or caped at a certain limit

### ISSUE THREAD

**Issue by Paul-B98** [helpwave/web#281]
The name of a room in a Station should be limited or the visualization should be capped at a certain limit.

![grafik](https://user-images.githubusercontent.com/115164840/233855279-dcf3bfb7-45fb-4030-b128-b2f0040835b7.png)

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer are there any limitation that are proposed by the backend? for example the min or max length of the room name

[Yes](https://wiki.helpwave.de/doc/task-OiAPDLSjyG). Room name: 1-32 chars.
