### ISSUE TITLE
Add a Add user modal

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#299]
add a function to add a user probably a modal, that also allows adding serveral useres at once

Design: https://github.com/helpwave/design/issues/1

**Comment by shivadharmi** [comment]
Hey @DasProffi. Can I work on this? Do we have a design?

**Comment by DasProffi** [comment]
@shivadharmi The design isn't ready yet, afterward of course you can work on it and sorry, I forgot to label it as not-ready

**Comment by MaxSchaefer** [comment]
See #475
