### ISSUE TITLE
Overlapping labels on small window size

### ISSUE THREAD

**Issue by florianjs** [helpwave/web#312]
![image](https://user-images.githubusercontent.com/54689374/234610044-ffd5c40d-4970-4df1-b866-b6376fc62d37.png)

![image](https://user-images.githubusercontent.com/54689374/234609473-be9be6a0-2740-4c40-b032-6048d78b08cb.png)

**Comment by MaxSchaefer** [comment]
@florian-sabonchi can you define "small window size"?

**Comment by florian-sabonchi** [comment]
Smaller than 700 pixels in width. I think this is a bug that we should fix in the long run. I think for now it is low priority

**Comment by Paul-B98** [comment]
@florian-sabonchi Maybe we should define a minimum supported window size? like 768px width

**Comment by use-to** [comment]
We actually discussed that earlier.

**Comment by use-to** [comment]
#193

**Comment by MaxSchaefer** [comment]
Okay, that's means that this issue will be "fixed" (swept under the carpet) when #193 is resolved.

**Comment by DasProffi** [comment]
@florian-sabonchi This was resolved by #193 or wasn't it?

**Comment by MaxSchaefer** [comment]
> swept under the carpet

Nope, just _swept under the carpet_ by declining access for small devices where this issue occurred. I have some To-dos with small optimization for improving tasks for tablets as well. The creation of this issue is pending.

**Comment by DasProffi** [comment]
Resolved on main
