### ISSUE TITLE
Task Template Screen

### ISSUE THREAD

**Issue by use-to** [helpwave/web#320]
- [ ] TwoColumn layout based screen
- [ ] Personal Task Template Screen (navigable using `UserMenu`)
- [ ] Ward Task Template Screen (navigable over WardDetailsScreen)

![Tasks - overview of Task Template in a wards](https://user-images.githubusercontent.com/13922835/235244016-7e6834d9-36af-4902-8156-60e86fce13d4.jpg)

**Comment by DasProffi** [comment]
This Screen should also contain a function to switch between personal and ward templates, otherwise it will be really confusing/annoying for a user to get to the right one
