### ISSUE TITLE
New organization pre-populated with wards

### ISSUE THREAD

**Issue by aegis301** [helpwave/web#325]
When the user creates a new orga, the created orga gets pre-populated with already created wards. This should not be the case.

**Comment by MaxSchaefer** [comment]
Thanks for the report. Looks like that the state for each organization gets shared among the other as well.

**Comment by DasProffi** [comment]
The organization and ward view are currently completely unrelated and always filled with the same dummy data. This will change with the connection of frontend and backend

**Comment by use-to** [comment]
#161
