### ISSUE TITLE
Backnavigation

### ISSUE THREAD

**Issue by aegis301** [helpwave/web#326]
Design Feedback: I find navigating back from the ward-level -> orga-level -> general-level a bit unintuitive, maybe we should implement a button or something like that for backnavigation?

**Comment by DasProffi** [comment]
> Design Feedback: I find navigating back from the ward-level -> orga-level -> general-level a bit unintuitive, maybe we should implement a button or something like that for backnavigation?

We have the breadcrump component next to the logo for that or where would you like to navigate to? @aegis301

**Comment by use-to** [comment]
#185

**Comment by aegis301** [comment]
The breadcrump was described as unintuitive by some test users. There should be a "back" button or something like that where you can navigate upwards in the "view tree"

**Comment by DasProffi** [comment]
> The breadcrump was described as unintuitive by some test users. There should be a "back" button or something like that where you can navigate upwards in the "view tree"

For a single back, you always have the browser's back button, but we can maybe try to actually show the tree structure maybe like this:
organization name
	- ward name
		- 	bed view

**Comment by DasProffi** [comment]
Maybe just renaming the bread crumbs to the acutal name of the ward/organization could also be an improvement

**Comment by MaxSchaefer** [comment]
> Maybe just renaming the bread crumbs to the acutal name of the ward/organization could also be an improvement

Good idea. I guess the name of a ward should be common sense in a hospital. Right? @aegis301

**Comment by DasProffi** [comment]
See #664
