### ISSUE TITLE
Auto-Save

### ISSUE THREAD

**Issue by aegis301** [helpwave/web#332]
The user should not be required to manually save tasks he or she created for a patient. Right now, if the user does not click "save changes", tasks and other status updates for the patient simply get deleted if the user does not hit "save changes" button. Maybe we should get rid of this button alltogether?

**Comment by MaxSchaefer** [comment]
To be consistent, we should move entirely to auto-save.

**Comment by DasProffi** [comment]
> To be consistent, we should move entirely to auto-save.

So every letter written is saved instantaneous?

**Comment by MaxSchaefer** [comment]
> > To be consistent, we should move entirely to auto-save.
> 
> So every letter written is saved instantaneous?

I don't think so. The first implementation can be proper debounce e.g. "no user input interaction for the last second (or two, or three, we will optimize this value further on), we save". The Save-Button should stay. We should notify the user with a small indication beside the Save-Button when an autosave occurs.
