### ISSUE TITLE
Autogenerate component boilerplate

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#344]
With the translation and component props we write some boilerplate, see the example of a component below. It would be nice to have a script or something to automatically generate this instead of copy and paste.

```typescript
import { tw } from '@helpwave/common/twind'
import type { Languages } from '@helpwave/common/hooks/useLanguage'
import type { PropsWithLanguage } from '@helpwave/common/hooks/useTranslation'
import { useTranslation } from '@helpwave/common/hooks/useTranslation'

type ComponentTranslation = {
}

const defaultComponentTranslation: Record<Languages, ComponentTranslation > = {
  en: {
  },
  de: {
  }
}

export type ComponentProps = {
}

/**
 * Description
 */
export const Component = ({
  language,
}: PropsWithLanguage<ComponentTranslation, ComponentProps>) => {
  const translation = useTranslation(language, defaultComponentTranslation)
  return (
    <div>
        // Your Code
    </div>
  )
}
```

The name that replaces `Component` above should be used as an input

### Implementation Details
Use a bash script that will be run via `next run generate <component name>`

**Comment by DasProffi** [comment]
For intellij users Settings->Editor->File Templates is a possibility

**Comment by MaxSchaefer** [comment]
Edgy idea ... We can also just move the boilerplate into the README ... 😆

**Comment by MaxSchaefer** [comment]
> a solution for this first has to be found, therefore this is a discussion

Add a bash script that gets executed by pnpm using a script like ` "gen:boilerplate": "./gen-boilerplate.sh"`.
