### ISSUE TITLE
Personal and Ward Task Templates uses same `queryKey`

### ISSUE THREAD

**Issue by use-to** [helpwave/web#364]
As the title already implies the personal and ward task template screen uses the same `queryKey` in React Query.
That leads to the same items displayed in that list.

**Comment by DasProffi** [comment]
What is the plan for the templates do we use an attribute to differentiate, whether it is a ward or personal template, then one key makes sense otherwise you are right that two keys are better

**Comment by use-to** [comment]
> What is the plan for the templates do we use an attribute to differentiate, whether it is a ward or personal template, then one key makes sense otherwise you are right that two keys are better

We wont request personal and ward tt using the same query/request endpoint. Besides its simply not possible it doesnt make any sense to me reusing the same cache for both screens.

I'm not sure what the best implementation is atm...

**Comment by DasProffi** [comment]
We could handle it with the same cache, but if we are going to have different endpoints anyway, it only makes sense having to mutations
