### ISSUE TITLE
Storybook for `lib`

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#375]
Over the past few weeks, [Storybook](https://storybook.js.org/) has been brought to the table time and time again. Before we roll out Storybook to `tasks`, we should evaluate it first with `lib`. This should step up our developer and product manager experience a lot.

- [x] Setup Storybook for `lib`
- [x] Create a Draft pull request
- [ ] Adopt components in Storybook
- [x] Deployment via Cloudflare Pages

**Comment by use-to** [comment]
@shivadharmi requested this earlier. Maybe you want to implement it?

**Comment by shivadharmi** [comment]
@use-to and @MaxSchaefer I can pick this and implement it.
