### ISSUE TITLE
AutoSave breaks Mutation

### ISSUE THREAD

**Issue by use-to** [helpwave/web#377]
https://user-images.githubusercontent.com/13922835/236709064-51c1a5ef-4673-4790-b988-34edfadeeb4b.mp4

**Comment by DasProffi** [comment]
Seems to be fixed on the current main. @use-to Is this still an issue? In that case, could you provide more information on what you did to reach this bug?

**Comment by use-to** [comment]
> Seems to be fixed on the current main. @use-to Is this still an issue? In that case, could you provide more information on what you did to reach this bug?

You're right! It's got fixed on current `main`.
