### ISSUE TITLE
Naming UUID or ID

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#378]
Sometimes we use UUID somtimes ID, we should check when what is appropriate

**Comment by Paul-B98** [comment]
@DasProffi can u provide a list or some examples for this

**Comment by use-to** [comment]
It is pretty clearly. We always use uuids as our primary identifier. We got some fuzzy logic in our current react query related code sections. This will get fixed later on #159

**Comment by DasProffi** [comment]
> @DasProffi can u provide a list or some examples for this

```
export type WardDTO = {id: string, ...}
```
and usage of wardUUID as a variable
`/organizations/${organizationUUID}?wardID=${wardUUID}`

It is just not clear, when and where we use what. The id of the Ward is a UUID but is called an ID here. We should be consistent. The same thing can be found for organization, task, task-template

**Comment by MaxSchaefer** [comment]
[On `services` we prefer `id`.](https://proto.helpwave.de/#proto.services.task_svc.v1.GetWardRequest)

**Comment by DasProffi** [comment]
Resolution: use id and fix all occurences of uuid to id
