### ISSUE TITLE
Horizontal Scrollbar issue

### ISSUE THREAD

**Issue by florianjs** [helpwave/web#379]
![image](https://github.com/helpwave/web/assets/54689374/c6e44a7c-9c71-463a-8df6-3d5fa7f9c491)

Horizontal scrollbars seem to be displayed in the station overview. DisplaySize seems to be 510 290

**Comment by florian-sabonchi** [comment]
![image](https://github.com/helpwave/web/assets/54689374/1b1b411c-1e74-471d-8295-57ccd785192e)
may be helpful for debugging purposes, since the error does not always occur.

**Comment by DasProffi** [comment]
What is meant by display size 510 290? @florian-sabonchi

**Comment by florianjs** [comment]
can be repoduced seem so to be at a screen resouliton of 1920 X 1003

**Comment by florianjs** [comment]
![Unbenannt](https://github.com/helpwave/web/assets/54689374/1e69dd63-531f-4257-88f7-4737e37ab66f)

**Comment by florianjs** [comment]
Me and Felix have worked out react-custom-scrollbars as a possible solution. For this reason we should switch to Me and Felix have worked out react-custom-scrollbars as a possible solution

**Comment by DasProffi** [comment]
closed by #670
