### ISSUE TITLE
new edit button for our Organization- and Ward-Card

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#384]
_See title_
We should discuss our approach first. Right now, our edit button is in the upper right corner, which makes the navigation quite hard.
![Bildschirm­foto 2023-05-09 um 9 26 34 PM](https://github.com/helpwave/web/assets/40192999/73c92c08-231e-449c-8be5-be93eda962b9)

**Comment by DasProffi** [comment]
We could try something like this:
![Ward Card (1)](https://github.com/helpwave/web/assets/67233923/3aad1303-e873-4dc5-ac61-3a09cd2aeac7)

**Comment by MaxSchaefer** [comment]
> We could try something like this (ignoring the different height): ![Ward Card (1)](https://user-images.githubusercontent.com/67233923/237353404-3aad1303-e873-4dc5-ac61-3a09cd2aeac7.png)

Looks good, the gray background should only be visible on hover.

**Comment by DasProffi** [comment]
> > We could try something like this (ignoring the different height): ![Ward Card (1)](https://user-images.githubusercontent.com/67233923/237353404-3aad1303-e873-4dc5-ac61-3a09cd2aeac7.png)
> 
> Looks good, the gray background should only be visible on hover.

Having a visible background is a better signifier for userinteraction, but we can try without one. (only on hover)

**Comment by use-to** [comment]
We shouldn't display the organisation name.
Free to implement...

**Comment by use-to** [comment]
We shouldn't display the organisation name.
Free to implement...
