### ISSUE TITLE
Cut off components when shrinking and then resizing the browser window

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#397]
![image](https://github.com/helpwave/web/assets/54689374/70ddd721-0817-4e9a-8e50-74f16f03cb48)

**Comment by Paul-B98** [comment]
i can't reproduce this behavior can u please explain how u did this?

**Comment by florian-sabonchi** [comment]
Hello, thanks for the response I also can no longer reproduce the error thus possibly fixed unknowingly. For this reason we can close the issue

**Comment by florian-sabonchi** [comment]
https://github.com/helpwave/web/assets/54689374/31b69596-4079-40d2-af5e-fe11395aaa0f

**Comment by florian-sabonchi** [comment]
Seems to still occur to reproduce it you need to reduce the window, so and then change the page e.g. from the organistaionsseite to the start page
