### ISSUE TITLE
switch to twind

### ISSUE THREAD

**Issue by JannikWibker** [helpwave/web#40]
> reference: https://twind.style & https://github.com/tw-in-js/twind

Twind is a replacement for Tailwind which is compatible with Tailwind's classname system but generates the styles on the fly. This removes one major annoyance with Tailwind, this being not being able properly work with conditional styles.
With SSR this isn't anything all too different from just using tailwind as the backend generates styles and hands these over to the client. The important difference now is that the client can continue to generate styles for new branches taken during execution.

Getting twind working just how you want it is somewhat complicated and requires a little bit of digging through source code

**Comment by MaxSchaefer** [comment]
Is twind a drop-in-replacement for tailwind? Does someone need knowledge of twind when he already knows tailwind?

**Comment by JannikWibker** [comment]
extremely minimal extra knowledge when it comes to just using it

take a look at the related PR:
- instead of `className="bg-slate-200"` you write `className={tw('bg-slate-200')}`
- if you previously needed to use classnames/clx use `tx` instead (no `tw` call)
- the config is in a different file but is almost identical

that's pretty much it

**Comment by MaxSchaefer** [comment]
Okay, I don't know twind but sound good I guess. We just want to minimize the onboarding costs for someone new in the project.
