### ISSUE TITLE
overflow on to large subtask description

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#410]
![image](https://github.com/helpwave/web/assets/54689374/520abb70-4036-41f4-a2f0-65eb8d60ce99)
we shoud set a fix size for subtask title to avoid a overflow

**Comment by Paul-B98** [comment]
@florian-sabonchi the size is fixed to a length of 64. Therefore i would argue that it might be better if the text wraps around if it gets to long to be displayed in one line. Also i would say that this is not a title but a description.

**Comment by florian-sabonchi** [comment]
Hi, thanks for your message I agree with you we could use e.g. text-ellipsis as text overflow. As for the title yes it is actually a description i have edited the title of the issue

**Comment by Paul-B98** [comment]
I think text-ellipsis is not a good solution because the description should be readable
