### ISSUE TITLE
Can we use `@twind/core` over `@helpwave/common/twind`?

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#430]

**Comment by DasProffi** [comment]
@JannikWibker Why did we create a new instance? Is it a necessity, or are there other ways to implement this?

**Comment by JannikWibker** [comment]
Without importing `@helpwave/common/twind` you won't have your custom config

The `@twind/core` instance has no config and you cannot easily set it and expect it to work in every place, for that you'll have to go through `@helpwave/common/twind` (afaik).
This is all kind of messy and fiddly, could be that there is another way to achieve this but as far as I know the current setup is the easiest to work with.

**Comment by DasProffi** [comment]
Okay then this issue will be closed
