### ISSUE TITLE
Overview of users invitations

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#434]
We need to have an overview to manage invitations for the current user. In this overview, the user should be able to accept and decline invitations. The overview should be s simple list of the invitations and lives inside the user menu.

**Comment by DasProffi** [comment]
Should be implemented as its own

**Comment by MaxSchaefer** [comment]
From our discussion:

- Own / seperate page
- Accessible via an entry in the user menu (upper right corner) "Invitations" / "Einladungen"
- A table of invitations. You can display a part of the ID as the name for now (until https://github.com/helpwave/services/issues/293 is done)
- Accept and decline invitations via this table
