### ISSUE TITLE
Indication of a private task

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#444]
To indicate a private task directly on our `TaskCard`, we should add a lock symbol to this card, as we already do it with scheduled ones.

![Bildschirm­foto 2023-05-26 um 9 25 34 PM](https://github.com/helpwave/web/assets/40192999/1e3bdd27-c6f1-478e-be3e-5d82351ae8d2)

**Comment by DasProffi** [comment]
We need discuss the order of icons and layout.

Current state there is only the progress indicator. If we add two addtional icon how do we display them? A column with progress, private, scheduled from top to bottom
