### ISSUE TITLE
Invite user into organization by email

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#475]
The button "Add member" on the organization details view, should open a simple modal where the user can enter an email address for the invitation.

The action buttons inside the modal should be "Invite", "Invite and next" and "Cancel".

- "Invite" should send the invite and closes the modal afterward
- "Invite and next" should send the invite and resets the modal afterward
- "Cancel" should close the modal

**Comment by DasProffi** [comment]
This isn't the best approach as the user cannot see which members are already in the organizations or which were already invited. Yet it seems okay as a first implantation.
