### ISSUE TITLE
Adopt `lib/Table`

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#494]
### Describe the chore

```[tasklist]
### Tasks
- [ ] #495
- [ ] #498
```

**Comment by MaxSchaefer** [comment]
@DasProffi can we also migrate the subtasks table/list on the task details view and task template details view to the new table?

**Comment by DasProffi** [comment]
> @DasProffi can we also migrate the subtasks table/list on the task details view and task template details view to the new table?

We would require the table to do some autosizing or manually make sure the height is okay since a scroll would be annoying, but other yes this is possible
