### ISSUE TITLE
Adopt `lib/Tables` on members table on organization details view

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#498]
### Describe the feature

Adopt `lib/Tables` on members table on organization details view

### Why is this feature needed?

because we have a new component for tables, which creates less overhead

**Comment by florianjs** [comment]
![image](https://github.com/helpwave/web/assets/54689374/4b9db966-c248-45c5-a2d7-d5c81a62b45b)
Looks like there are problems in this feature with editing the organisations if necessary. Should you look at this again

**Comment by DasProffi** [comment]
> Looks like there are problems in this feature with editing the organisations if necessary. Should you look at this again

Please explain the problem rather than just saying there is one

**Comment by florianjs** [comment]
> > Looks like there are problems in this feature with editing the organisations if necessary. Should you look at this again
> 
> Please explain the problem rather than just saying there is one
Sorry, the problem i can no longer edit the name of an organization. Also there is a display error in the member list see screenshot. I have not yet looked at the cause
