### ISSUE TITLE
Replace listing of ward names with amount of members on organization card

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#501]
### Describe the chore

![Bildschirm­foto 2023-07-12 um 8 07 32 PM](https://github.com/helpwave/web/assets/40192999/9f0ba0de-fca0-4959-926e-b75ca881a5fb)

**Comment by DasProffi** [comment]
![Organization Card_hover](https://github.com/helpwave/web/assets/67233923/cd503403-a2ef-4600-a4fc-180740e1eb15)
Maybe this would be better, because the member information are all in the bottom row and not split across two
