### ISSUE TITLE
Bread crumb menu: Use the name of the current entity

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#512]
### Describe the feature

For example: When the user is on the ward overview, the name of the room, ward and organization should be inside the bread crumb menu instead of the generic entity names.

### Why is this feature needed?

To increase user experience

**Comment by DasProffi** [comment]
We do not have all name information on the screens e.g. the `ward/<uuid>` only has access to the ward name, but not the organization name. Therefore the breadcrumbs /organization/ward/rooms cannot be fully resolved to the real names.

Adding this information to the endpoint or making an additional request just for this name seems not a good solution.

**Comment by DasProffi** [comment]
See #664
