### ISSUE TITLE
Remove room description if no beds have been assigned

### ISSUE THREAD

**Issue by florianjs** [helpwave/web#526]
### Describe the feature

I suggest removing the name of a room from the room overview if no beds have been assigned.

### Why is this feature needed?

Information that is not required should also not be displayed in my opinion

**Comment by florianjs** [comment]
![image](https://github.com/helpwave/web/assets/54689374/d8a5c3e4-d503-4564-be99-26c577b0acba)

**Comment by MaxSchaefer** [comment]
Was introduced again in https://github.com/helpwave/web/pull/564/files

**Comment by MaxSchaefer** [comment]
@florianjs we should remove the whole room instead of removing just the title if there are no beds. https://github.com/helpwave/web/blame/e8f9d5423623ce76f2c46b77de6f43bd1295b62e/tasks/components/RoomOverview.tsx#L33
