### ISSUE TITLE
Query inconsistency

### ISSUE THREAD

**Issue by use-to** [helpwave/web#528]
### Describe the bug

[query_bug_on_quick_change.webm](https://github.com/helpwave/web/assets/13922835/514ad5c7-b135-48b0-8896-10d01573f04f)

The query process causes a "flicker" and inconsistent response.

### Describe how to produce the bug

Just switch the bed selection fast enough.

**Comment by MaxSchaefer** [comment]
We've talked about this. We should optimize the react-query keys.
