### ISSUE TITLE
Transform Overview Page

### ISSUE THREAD

**Issue by use-to** [helpwave/web#538]
### Describe the feature

Swap the organization with recent wards and the ward list with recent patient cards (unassinged or assigned - not discharged).

### Why is this feature needed?

As a user is mostly focused on patients and wards of one organization, we should reorder the overview page.

**Comment by DasProffi** [comment]
How do we store and retrieve the recent wards an patients, for wards there is a endpoint, but for just patients there isn't

**Comment by use-to** [comment]
> 

Right, we may implement new endpoints in services.

**Comment by use-to** [comment]
> 

Right, we may implement new endpoints in services.

**Comment by use-to** [comment]
> How do we store and retrieve the recent wards an patients, for wards there is a endpoint, but for just patients there isn't

Right, we may implement new endpoints in services.

**Comment by DasProffi** [comment]
I marked it as not ready till then
