### ISSUE TITLE
Visibility for task

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#558]
### Describe the feature

Re-Enable the public/private-flag logic again and sync the field with the API.

### Why is this feature needed?

The user needs to set private and public tasks.

### Additional context

[The logic was disabled by this pr.](https://github.com/helpwave/web/pull/520)

**Comment by DasProffi** [comment]
this flag is only settable on create or how are afterward changes handled?

**Comment by DasProffi** [comment]
only one way, private to public
