### ISSUE TITLE
duplicated Organisation selection on reload page 

### ISSUE THREAD

**Issue by florianjs** [helpwave/web#559]
### Describe the bug

if the page is reloaded ore the back button of the browser for example Google Chrome or Chromium on the organisation view multiple organistaion are selected 

### Describe how to produce the bug

reload the page on the organisation view

### Additional context

![image](https://github.com/helpwave/web/assets/54689374/542bf7f0-ed75-4d88-9b7f-0e71b053f4f0)

**Comment by DasProffi** [comment]
This is a backend issue, because the same organization is returned twice
see #576
