### ISSUE TITLE
Scaling when resizing the orga window

### ISSUE THREAD

**Issue by Paul-B98** [helpwave/web#563]
### Describe the bug

When the orga plain is resized the orga tiling is reduced and not expanding

### Describe how to produce the bug

resize the orga plain

### Additional context

![grafik](https://github.com/helpwave/web/assets/115164840/bf878241-16d7-470f-9d83-9dfcb2eaa805)

![grafik](https://github.com/helpwave/web/assets/115164840/43f45cd3-8092-4bba-8a91-7b4acf6ccc7f)

**Comment by Paul-B98** [comment]
@DasProffi The issue is that we scale the number of columns with the size... i would propose that we fix the columns at 3

**Comment by DasProffi** [comment]
maybe should set a maximum at 3 or 4, but still keep the scaling, because 3 colums is bad when the right is maximized

**Comment by Paul-B98** [comment]
okay the i set the max size to 3

**Comment by Paul-B98** [comment]
> maybe should set a maximum at 3 or 4, but still keep the scaling, because 3 colums is bad when the right is maximized
@DasProffi the thing is that becaus of the min size nothing smaller than 3 is nessasary

**Comment by DasProffi** [comment]
> > maybe should set a maximum at 3 or 4, but still keep the scaling, because 3 colums is bad when the right is maximized
> > @DasProffi the thing is that becaus of the min size nothing smaller than 3 is nessasary

Then we should still keep the scaling, so the min size can be adjusted as needed
