### ISSUE TITLE
No limits for Bed name

### ISSUE THREAD

**Issue by Paul-B98** [helpwave/web#566]
### Describe the bug

there is no limit for a bed name which could create some visual effects

### Describe how to produce the bug

add some chars to the bed name

### Additional context

![grafik](https://github.com/helpwave/web/assets/115164840/ec6c9b0f-6dd1-46cd-a65b-d3d8e32a828b)

**Comment by florianjs** [comment]
Hello what limit are you proposing? We should also implement the limit in the backend at the same time @Paul-B98

**Comment by DasProffi** [comment]
> Hello what limit are you proposing? We should also implement the limit in the backend at the same time @Paul-B98

Just set it to 24 or 32 for now, that should neither be too low or high

**Comment by MaxSchaefer** [comment]
https://wiki.helpwave.de/doc/task-OiAPDLSjyG 16 chars
