### ISSUE TITLE
There is no limit for a patient name

### ISSUE THREAD

**Issue by Paul-B98** [helpwave/web#570]
### Describe the bug

There is no limit for the patient name when assigned to a bed which creates some visual problems

### Describe how to produce the bug

add as many chars as you want ot the name of a patient when assining to a bed

### Additional context

![grafik](https://github.com/helpwave/web/assets/115164840/559f4ca4-af6c-41f1-bda1-e515cea653e5)

**Comment by Paul-B98** [comment]
@DasProffi what should we us as a limit?

**Comment by DasProffi** [comment]
> @DasProffi what should we us as a limit?

Something between 24 and 48 seems reasonable, maybe take 48 just to be safe
