### ISSUE TITLE
Task and Tasktemplate title length differs

### ISSUE THREAD

**Issue by Paul-B98** [helpwave/web#571]
### Describe the bug

the max length of a title differs for a task and the corresponding template. The task has a max length of 32 and the template of 64

### Describe how to produce the bug

create a task tmeplate with max chars and then a task out of it

**Comment by Paul-B98** [comment]
@DasProffi what limit should we use?

**Comment by DasProffi** [comment]
> @DasProffi what limit should we use?

Take the lower bound 32 for now
