### ISSUE TITLE
possible to select a used bed

### ISSUE THREAD

**Issue by florianjs** [helpwave/web#575]
### Describe the bug

In the bed selection a bed is shown which is already in use if a bed is selcted that is in use error is occuring

### Describe how to produce the bug

Go to Room Overview Selct a beed that is already in use 

### Additional context

![image](https://github.com/helpwave/web/assets/54689374/c608bc64-4314-4e3a-870f-20d0d9737ee8)

**Comment by MaxSchaefer** [comment]
We should gray out non-available beds
