### ISSUE TITLE
Ensure uniqueness across react-query keys

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#576]
### Describe the bug

```
Warning: Encountered two children with the same key, `3b25c6f5-4705-4074-9fc6-a50c28eba406`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

### Describe how to produce the bug

Open the JavaScript console of [current main](https://github.com/helpwave/web/tree/cb4b900e844fcb33633c14835f7770e39523f640).

### Additional context

https://helpwave.slack.com/archives/C045573RX9P/p1691000001427579

**Comment by DasProffi** [comment]
this is an backend issue, see https://github.com/helpwave/services/issues/320
