### ISSUE TITLE
Task template navigate to Organization error

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#602]
### Describe the bug

Switching from the task template page to the organisation leads to errors when loading the organisation

### Describe how to produce the bug

go to personal task template click the link for organisation

### Additional context

[Bildschirmaufzeichnung vom 2023-08-09, 20-55-21.webm](https://github.com/helpwave/web/assets/54689374/dd9dc586-ff5a-4d7b-99de-6c614e36841c)

**Comment by DasProffi** [comment]
We currently have no good way of getting the organization_id in this ward/templates view, this results in using the default org1, which doesn't exist.

What solution do you suggest? @MaxSchaefer 
- use an organization id from the token claims (Q: Which one and does it always exist?)
- endpoint to fetch this information
- removal from the bread crumbs

**Comment by MaxSchaefer** [comment]
Please fallback to the default `/organizations` route until we are able to resolve the org via the breadcrumbs.

**Comment by DasProffi** [comment]
See #664

**Comment by DasProffi** [comment]
fixed on main
