### ISSUE TITLE
Feedback Form

### ISSUE THREAD

**Issue by aegis301** [helpwave/web#624]
### Describe the feature

We should have a feedback form in a prominent place in the frontend. This is used by users to report bugs and give suggestions for additional features. The form sould contain:

- a dropdown menu with "Fehlermeldung", "Anregung" und "Sonstiges" as selectables.
- a text field

### Why is this feature needed?

Especially in the piloting phase, we need a low-key way for users to send feedback to us.

### Additional context

Maybe changing placeholders for the textfield would be nice?

"Fehlermeldung" -> Mir ist aufgefallen dass...
"Anregung" -> Ich würde mir wünschen dass...
"Sonstiges" -> Was du uns sonst noch mitteilen wolltest...

**Comment by MaxSchaefer** [comment]
I will provide a HubSpot integration for that.
