### ISSUE TITLE
Dismissed patients click error

### ISSUE THREAD

**Issue by florianjs** [helpwave/web#633]
### Describe the bug

Opening the patient list and then clicking on the list or discharged patients leads to an error

### Describe how to produce the bug

go to room overview click the left button patient list then click on dischard patient or drag and drop to one room

### Additional context

[Bildschirmaufzeichnung vom 2023-08-16, 12-18-58.webm](https://github.com/helpwave/web/assets/54689374/1a6b37f0-109c-4430-9f16-808b9919b9b7)

**Comment by DasProffi** [comment]
This is caused by the backend, retrieving information or assigning a discharged patient is currently permitted
@MaxSchaefer How do we want to resolve this?
- disallow dragging and clicking on discharged patient
- implement the functionality in the backend

**Comment by MaxSchaefer** [comment]
For now _disallow dragging and clicking on discharged patient_ would be fine.
