### ISSUE TITLE
Restructure landing-page

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#64]
- Merge teams and partners sections
- Remove roadmap sections
---
- Set default language to german
- Merge contacts with a new text sections
- Shorten feature texts

**Comment by SrJonassss** [comment]
u want more? (titel)


(ab hier dann Text)
Du kannst schon heute Teil der **_helpwave-Familie_** werden und uns auf unserem Weg zu einem innovativen Gesundheitswesen begleiten. 
Melde dich dafür einfach direkt hier an!

Note: Das hier in kursiv und fett gedruckte bitte mal ausprobieren, ob das mit einer Akzentfarbe gut aussehen könnte.

**Comment by SrJonassss** [comment]
ToDos: 

1. Logo in den Header einfügen (auf Höher der Navigation)
2. Navigation aufräumen (Roadmap rausstreichen)
3. Text neben dem HubSpot einfügen 

Danke
