### ISSUE TITLE
Patient List showing all Patients

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#663]
### Describe the bug

The patient list shows all patients of all wards instead of only the patients of the selected ward.

### Describe how to produce the bug

Create two patients on different wards, go to one ward and click on the patient list to see the patients of another ward as well.

### Additional context

![image](https://github.com/helpwave/web/assets/54689374/d525964b-491b-42d8-8145-f9e3291469ea)

**Comment by DasProffi** [comment]
Patients are seen organization wide and not ward wide. This is intended behavior. But we might start a discussion regarding this

**Comment by florianjs** [comment]
Okay, got it, find this quite confusing

**Comment by use-to** [comment]
#707
