### ISSUE TITLE
Empty Ward

### ISSUE THREAD

**Issue by aegis301** [helpwave/web#666]
### Describe the feature

If a ward is empty it looks...well...empty. There is no call to action for the user to guide him or her what to do now. Maybe a disclaimer text in the concept of "This ward has currently no beds assigned to it. Go back to the wards menu and edit your ward to assign beds. You most likely only have to do this once." would be a good idea?

### Why is this feature needed?

Users will find themselves on an empty ward and will not know what to do from here. Some guidance would be good for user experience.

**Comment by DasProffi** [comment]
Add a Text when the ward contains no rooms to the room overview. Linking back to the Ward details, so that the user can add rooms and beds
