### ISSUE TITLE
Hard-coded organization links

### ISSUE THREAD

**Issue by use-to** [helpwave/web#668]
### Describe the bug

There are still link directing to `org1` as it is hard-coded in our repository

### Describe how to produce the bug

1. Open a ward overview screen.
2. Click on the bread crumbs displayed in the top bar. (`Ward`)
3. This redirects you to `https://tasks.helpwave.de/organizations/org1?wardId=<uuid>`
4. Just loading as `org1` is not a valid uuid.

**Comment by DasProffi** [comment]
Will be resolved with #664
