### ISSUE TITLE
Every member is my own name

### ISSUE THREAD

**Issue by use-to** [helpwave/web#671]
### Describe the bug

The member list only shows myself `n`-times.

### Describe how to produce the bug

Click on "Organization Details" (look at the member list). You need more than 1 member in your organization in order to reproduce this bug.

**Comment by use-to** [comment]
@MaxSchaefer Staging is working, production not? Why? Could you please resolve and maybe close this issue if applied on production?

**Comment by use-to** [comment]
Still a problem: ![image](https://github.com/helpwave/web/assets/13922835/e0ce58e4-40bd-4622-842f-548d64b5ef11)

**Comment by DasProffi** [comment]
Did you invite other people or just yourself multiple times? The latter would be backend issue.

Or in general, what did you do before to get this result?

**Comment by use-to** [comment]
> Did you invite other people or just yourself multiple times? The latter would be backend issue.
> 
> Or in general, what did you do before to get this result?

@DasProffi Try it yourself, I feel like I don't have to provide testing instructions for this, but here you go:
1. Login into https://tasks.helpwave.de/
2. Create a new organization (called what every you want)
3. Invite another user (preferably a person with a different name, so that you also see that your concern is unnecessary)
4. (Impersonate other the user) Click on accept
5. Open up organization detail view and take a look at the members.

I anticipate that if you assign an issue yourself, you would make an attempt to thoroughly investigate the error and make an effort to replicate it manually.

Since this error also occurs in the selection of the assignee for a task, I strongly suspect that this is not a mere UI bug but rather deeply embedded within the logic, possibly even a backend issue. It would be advisable to conduct a thorough triage of this situation.

![image](https://github.com/helpwave/web/assets/13922835/6adadb80-dc7d-4935-a13f-c70a5fb465d6)

**Comment by use-to** [comment]
> Did you invite other people or just yourself multiple times? The latter would be backend issue.
> 
> Or in general, what did you do before to get this result?

I wonder if you or anyone else ever got this working by inviting another person...

**Comment by DasProffi** [comment]
It's a backend issue, I will open a bug report

**Comment by FoseFx** [comment]
Confirmed fixed via https://github.com/helpwave/services/pull/466
