### ISSUE TITLE
Continuously refetching using `refetchInterval` on `useQuery()`

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#679]
### Describe the feature

We could set a default `refetchInterval` for every `useQuery()` hook via the [Default Query Function](https://tanstack.com/query/v4/docs/react/guides/default-query-function). The passed `refetchInterval` should be configurable via the config and defaults to five seconds.

[`refetchInterval` on `useQuery()`](https://tanstack.com/query/v4/docs/react/reference/useQuery)

### Why is this feature needed?

To enable more real-time collaboration in helpwave tasks we should update / refetch the state more often. React Query can help use with that by automatically refetching after a specific time.

**Comment by DasProffi** [comment]
@MaxSchaefer is this still something we want to implement?
