### ISSUE TITLE
Patients can't be opened once discharged

### ISSUE THREAD

**Issue by 00100200345** [helpwave/web#689]
### Describe the bug

When a patient is discharged, the patient cannot be opened again, so no information on which tasks were performed etc is available and if the discharged happened accidentally, there is no way back. 

### Describe how to produce the bug

create patient, add tasks, discharge patient.

**Comment by DasProffi** [comment]
Discharging a patient currently equals a delete from the user perspective. This will change later, but is blocked by the backend right now

**Comment by use-to** [comment]
Isn't this already fixed?

**Comment by DasProffi** [comment]
> Isn't this already fixed?

No the backend doesn't return a discharged patients.
See https://github.com/helpwave/services/issues/475

**Comment by PaulKalho** [comment]
should be ready now @DasProffi :)
