### ISSUE TITLE
ward does not show correct number of beds/tasks

### ISSUE THREAD

**Issue by 00100200345** [helpwave/web#692]
### Describe the bug

Ward overview does not show correct number of beds or tasks. I have added three rooms with 6 beds in total and multiple tasks. When going back to the ward level, this is not reflected in the ward "card". 

### Describe how to produce the bug

create ward, add rooms and tasks. Go back to ward page.

**Comment by aegis301** [comment]
@MaxSchaefer is this issue being adressed?

**Comment by use-to** [comment]
[Error description](https://github.com/helpwave/web/assets/13922835/58063d60-920d-4b22-9c79-035de1ce6ade)

**Comment by use-to** [comment]
Video footage of error:

[Screencast from 2023-09-29 18-45-14.webm](https://github.com/helpwave/web/assets/13922835/13d4c31a-ccc0-400a-a1a8-d833dfa22b3d)

**Comment by MaxSchaefer** [comment]
Will be solved by https://github.com/helpwave/services/pull/395
