### ISSUE TITLE
The memberlist isn't shown in OrganizationDetails

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#700]
### Describe the bug

The memberlist isn't shown in OrganizationDetails

### Describe how to produce the bug

Load the OrganizationDetails

### Additional context

introduced in #652

**Comment by MaxSchaefer** [comment]
Fixed? https://github.com/helpwave/web/pull/701#issuecomment-1703970753

**Comment by DasProffi** [comment]
> Fixed? [#701 (comment)](https://github.com/helpwave/web/pull/701#issuecomment-1703970753)

Yes, but in a way that is not easy to understand and that makes the component's behavior hard to determine. Additonally unintend side effects might occur. A solotion was provided in the pr
