### ISSUE TITLE
Closing buttons

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#703]
### Describe the feature

We should add a closing button to all modals such as the invitation dialog

### Why is this feature needed?

To improve the usability

### Additional context

![image](https://github.com/helpwave/web/assets/54689374/019eddbd-7dfa-4966-940f-1958d554e7ce)

**Comment by DasProffi** [comment]
Maybe also fix consistency issue that were mentioned in #709

**Comment by DasProffi** [comment]
## Implementation
- implement it as a generic modal header, which takes a `React.Node` and a `onClose` function.
