### ISSUE TITLE
website not working in Split View (macOS)

### ISSUE THREAD

**Issue by 00100200345** [helpwave/web#705]
### Describe the bug

When using Split View in safari, the website shows landing page I get when trying to open the website on mobile device 

<img width="834" alt="Bildschirmfoto 2023-09-03 um 14 22 34" src="https://github.com/helpwave/web/assets/45564549/bc7d02b6-4111-45e6-96ad-d5091ed0ef8b">

### Describe how to produce the bug

Open tasks.helpwave.de (in fullscreen or window), log in, then set up split view.

**Comment by DasProffi** [comment]
We currently have a window size restriction of 1350px width as we don't have fully dynamic window sizing. If your window size is lower than 1350px, you will see this screen.

This issue is thus not mac exclusive, but occurs on Windows or any other device all the same.

**Comment by DasProffi** [comment]
For now the only solution is to make your window wider. We will reenable the site for lower width devices later or display a proper message for pc users, indicating this issue.

@MaxSchaefer What is your opinion on this?

**Comment by 00100200345** [comment]
Ok, thanks. As long as it works on "normal" pc displays, everything should be fine

**Comment by DasProffi** [comment]
Will be resolved in #742
