### ISSUE TITLE
due date of task switching to 01.01.1970 when not assigned initially

### ISSUE THREAD

**Issue by 00100200345** [helpwave/web#708]
### Describe the bug

When creating a new task without assigning a due date, the due date switches to 01.01.1970 when re-opening that task later.

### Describe how to produce the bug

Create task, set no due date, close task, re-open it.

**Comment by use-to** [comment]
We should set it to the current date + 3 hours or something like that.

**Comment by 00100200345** [comment]
I don't think an average time can be estimated. Current date makes sense, time wise: maybe leave it at the time of creation? As long as setting a due time has no effect on how the tasks are presented, setting a specific time is not that important, I assume.
