### ISSUE TITLE
Faster deletion of default text

### ISSUE THREAD

**Issue by yeahmoin** [helpwave/web#714]
## What
After editing subtasks in task templates, it would be helpful to select the default text "new subtask" after clicking the pencil, to delete it even faster

## Why
Faster creation of subtasks when

**Comment by DasProffi** [comment]
Possible Solution: https://stackoverflow.com/questions/4067469/selecting-all-text-in-html-text-input-when-clicked

Make it generic for the toggleable input as an attribute
