### ISSUE TITLE
Task completion in task view

### ISSUE THREAD

**Issue by yeahmoin** [helpwave/web#716]
## What
Additionally to setting task to "done" via drop-down, a button or checkbox to finish a task (similar to subtasks) would be grand 

## Why
One more way to finish tasks and give users choice

**Comment by DasProffi** [comment]
Should be done with issue #690

**Comment by DasProffi** [comment]
## Implementation
Add a finish button in task detail view

**Comment by florianjs** [comment]
I am not a fan of implementing functionalities multiple times. With this button we now have 3 ways to set a task to completed

**Comment by 00100200345** [comment]
I would generally agree. However, IMO, the handling of finishing tasks is inconsistent atm  - for subtasks, there are checkboxes, for tasks without subtasks or with all subtasks done, drop down menus (requiring more actions - I would always prefer one-click options from user's perspective). The categorical difference between subtasks and tasks that make this difference necessary is not obvious at this point, I think.
