### ISSUE TITLE
Add Pill / Label component

### ISSUE THREAD

**Issue by JannikWibker** [helpwave/web#72]

**Comment by use-to** [comment]
https://github.com/helpwave/mobile-app/issues/214

**Comment by DasProffi** [comment]
This Pill ![Pill](https://user-images.githubusercontent.com/67233923/222854679-a308dd7a-f9fd-49f9-940f-bed4f2d9fd81.png) or this one ![task pills](https://user-images.githubusercontent.com/67233923/221577028-69ac7c5a-f6be-4ed0-b82c-8f579147f357.png)?
