### ISSUE TITLE
Order of subtasks changing

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#726]
### Describe the bug

Oder of subtasks is changing if a new subtask is added

### Describe how to produce the bug

Go to the task view go to and task and add some subtasks the order will change

### Additional context

Probably not a bug but is a little bit confusing

**Comment by florianjs** [comment]
In my opinion, it would make sense to sort the subtasks so that newly added ones are always at the end. We should realize this by a sorting in the backend, but for this we would need a field, which stores the creation date.
