### ISSUE TITLE
Recent patients

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#740]
### Describe the feature

The client can retrieve the recent patients by [this new endpoint](https://proto.helpwave.de/#proto.services.task_svc.v1.GetRecentPatientsRequest). The new `RecentPatientCard` should contain similar information as a row in the patient list.

- Name of the patient
- Room and bed

The on-click behavior should navigate the user diretly to the patient on the ward overview. Right now, the ward_id is not part of the response. Until this issue is resolved, please fetch the ward_id after the on-click via https://proto.helpwave.de/#proto.services.task_svc.v1.GetRoomRequest.

### Why is this feature needed?

For faster navigation

**Comment by DasProffi** [comment]
What should be the behavior for unassigned or discharged patients? Which ward are they shown in?
