### ISSUE TITLE
Avatar icon in task card

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#770]
### Describe the feature

The avatar icon should be added to the task card as visible in the mock https://github.com/helpwave/design/issues/8#issuecomment-1763477668.

### Why is this feature needed?

To give the user a sense if a task is assigned or not.

### Additional context

Until https://github.com/helpwave/services/issues/476 is finished, you can use https://source.boringavatars.com/marble/128/ for a reference icon and open a draft pr.

**Comment by DasProffi** [comment]
We probably won't save the assignee avatar url in the task object, but instead would fetch it for each card otherwise we will have yet another Task type and maybe need to change other components aswell to do the passing of the objects
