### ISSUE TITLE
Updating tasks does not close pop-up window

### ISSUE THREAD

**Issue by 00100200345** [helpwave/web#782]
### Describe the bug

When updating a task, i.e. after completing a sub task, the pop-up window is not closed. This is opposed to the behavior when choosing "delete" or "finish"

### Describe how to produce the bug

Create task with subtasks. Re-open it and complete subtask. Then click update. 

### Additional context

The behavior of "delete", "finish" and "update" is inconsistent with regards to what happens to the pop-up window.

Also, from a users perspective, it is unclear whether changes are saved only if the task has been "updated" manually. The function of this option is thus unclear. It overlaps with the close option. 

Either automatically save all changes (then, a specific update button seems unnecessary) and somehow include the option to discard changes if not wanted or include a "save" or "update" button to make sure changes are saved but alter function of the "close" option, potentially including the option to discard changes or keep them.

**Comment by DasProffi** [comment]
@MaxSchaefer This issue regards save behavior for which have not specified a clear approach other than autosaving. Options like discarding/undoing changes were not considered till now. Maybe we can find a method for connecting this to our service approach of saving the changes

**Comment by DasProffi** [comment]
We will use only autosaves for now. Reverts have to be done manually and will be added later on.

Thus the **update button should be delted**

**Comment by DasProffi** [comment]
Reverts will be regarded in #956
