### ISSUE TITLE
Weird preconfigured date for tasks

### ISSUE THREAD

**Issue by aegis301** [helpwave/web#798]
### Describe the bug

There seems to be a weird preconfigured date in place for a task so that the default scheduling is the next day, a couple of hours ahead, sometimes in the middle of the night.

### Describe how to produce the bug

Create a new task

**Comment by DasProffi** [comment]
Currently, the date will be set to +6hrs regardless of the time of day or weekday.

What would you prefer instead, or should this field have no value as a default? @aegis301
