### ISSUE TITLE
Room sorting in patient detail view

### ISSUE THREAD

**Issue by aegis301** [helpwave/web#801]
### Describe the bug

When reassigning a patient to another room in the patient detail view, the rooms arent always ordered numerically.

### Describe how to produce the bug

Reassigning a patient in a ward with multiple rooms

**Comment by DasProffi** [comment]
We have switched to custom room names thus it is up to the user to create the ordering and this is not an issue anymore

**Comment by DasProffi** [comment]
On the RoomOverview the Rooms were still alphabetically ordered, which overwrites the ordering. Thus it should be removed to only rely on the user input names
