### ISSUE TITLE
modal not centered

### ISSUE THREAD

**Issue by florian-sabonchi** [helpwave/web#808]
### Describe the bug

modal for editing subtasks is not centerd 

### Describe how to produce the bug

go to a patient and add a subtasks

### Additional context

![image](https://github.com/helpwave/web/assets/54689374/8a1eef20-9372-4c33-a3d4-7b988be4061a)

**Comment by DasProffi** [comment]
This was intended and explicitly wanted by @use-to, so the main area is always centered.
