### ISSUE TITLE
Fail layout

### ISSUE THREAD

**Issue by corners2wall** [helpwave/web#844]
### Describe the bug

When I swipe window to a half then layout feels badly
[Screencast from 29.01.2024 21:56:26.webm](https://github.com/helpwave/web/assets/110557519/df0de8c4-e723-4297-aad6-5da11532f9b4)

### Describe how to produce the bug

Watch video

**Comment by use-to** [comment]
related to #749

**Comment by corners2wall** [comment]
let me fix it so there is no overflow on tablet device

**Comment by use-to** [comment]
> let me fix it so there is no overflow on tablet device

Just assigned you @corners2wall. Feel free, create a PR and request my review.

**Comment by MaxSchaefer** [comment]
@corners2wall thanks for taking over this issue. Any progress here?

**Comment by corners2wall** [comment]
@MaxSchaefer  nope
