### ISSUE TITLE
Pseudo markdown to HTML Parser

### ISSUE THREAD

**Issue by DasProffi** [helpwave/web#852]
### Describe the feature

A Component that parses pseudo markdown (**see context**) to HTML components.

### Why is this feature needed?

To allow for dynamically loading and creating content on the landing page

### Additional context

For example \b{text} will be shown as **text** or \i{\u{underline} and italic} as _<ins>underline</ins> and italic_

| feature| marker |
|--------|--------|
| italic | \i |
| bold | \b |
| underline | \u |
| strike-through | \s |
| red | \red |

**Comment by JannikWibker** [comment]
Why not just go with regular (inline) markdown?, for `red` you could go with `==highlight==` and just style that through css

([markdown-it](https://github.com/markdown-it/markdown-it) + [markdown-it-mark](https://www.npmjs.com/package/markdown-it-mark) + [markdown-it-underline](https://www.npmjs.com/package/markdown-it-underline), you'd have to do some small adjustments to only allow inline markdown features though)

Writing your own parser for something like this sounds like a small nightmare w.r.t. escaping and code injection/xss

**Comment by DasProffi** [comment]
> Why not just go with regular (inline) markdown?, for `red` you could go with `==highlight==` and just style that through css
> 
> ([markdown-it](https://github.com/markdown-it/markdown-it) + [markdown-it-mark](https://www.npmjs.com/package/markdown-it-mark) + [markdown-it-underline](https://www.npmjs.com/package/markdown-it-underline), you'd have to do some small adjustments to only allow inline markdown features though)
> 
> Writing your own parser for something like this sounds like a small nightmare w.r.t. escaping and code injection/xss

The plan is to allow for custom shorthands and individual additions to use it in custom translations that are also styled per translation.

This feature is used to avoid writing HTML inside a translation therefore there are no code injection issues. Just complex string parsing.

Additionally, this shall be used to unify styling; for example, the `\helpwave` command will always write helpwave in space grotesk and bold to highlight it. Similarly, colors don't have to be copied again and again. Instead, a simple set of predefined colors is used.

But it is definitely worth considering to use and adapt a different parser to our needs, especially if we decide to support links and other features

**Comment by MaxSchaefer** [comment]
I go with both of you. If we need to be more complex as https://github.com/helpwave/web/pull/877, we should evaluate third-party libs first.
