### ISSUE TITLE
Properties list

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#862]
The properties list will contain the properties of a subject. Every row must hold the key/value pair. The value column can also be editable via a custom interaction. The goal of this issue is to provide a list that supports these use cases. The different data types are not part of this issue. You can use our already existing Text and Date Inputs for testing.

Open a PR if you need to discuss the data structure first.

https://www.figma.com/file/4oxQRRLaNQ1TdBVhI0CZ4B/helpwave-frontend?type=design&node-id=2922-1516&mode=design&t=Uk0xFATkYqIhwZH0-4
![Image](https://github.com/helpwave/web/assets/40192999/1a018aa1-d32d-4fac-b929-5713a268b934)

**Comment by DasProffi** [comment]
I will split this into several issues to decrease the workload

**Comment by DasProffi** [comment]
Branches implementing this are merged. See #887
