### ISSUE TITLE
Endorsement page

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#867]
### Describe the feature

This page should display our animated ring component to give some sense of outreach. On the right side the visitor should have the ability to sign-up for our newsletter. I've created a "wireframe".

![Frame 74](https://github.com/helpwave/web/assets/40192999/c2123afc-751d-45e5-aed4-976cbb56dc88)

### Why is this feature needed?

The endorsement page should be our "outcall" page to give our supporters the ability to show the endorsement.

### Additional context

"Endorsement" ... support page would be in conflict with actual support requests. Open for suggestions.

_No response_

**Comment by MaxSchaefer** [comment]
I am unsure about the background for the text and newsletter form ... something glassy? @DasProffi

**Comment by MaxSchaefer** [comment]
@use-to could you provide content for "Text 1" and "Text 2"?

**Comment by DasProffi** [comment]
> I am unsure about the background for the text and newsletter form ... something glassy? @DasProffi 

We can do that, maybe also just a gray background would be sufficient
