### ISSUE TITLE
Property details

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#883]
These three input groups (https://github.com/helpwave/web/issues/882) are all part of the property details layout. This layout should accept property data to be edited via these input groups. All changes are auto-saved.

The Field-Section Field-Type-Selector can just contain "Text" option right now. Later types will follow soon.

https://www.figma.com/file/4oxQRRLaNQ1TdBVhI0CZ4B/helpwave-frontend?type=design&node-id=3059-1578&mode=design&t=WISz1uPxaiY2qaH1-4
![Image](https://github.com/helpwave/web/assets/40192999/2b478f0e-bbe3-4e0c-ac27-af56f561bcae)

**Comment by DasProffi** [comment]
Closed by #904
