### ISSUE TITLE
Create property form

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#928]
If the user clicks on the `Add property` button, the right column displays the "New property" form. The formular contains input groups. The first input group is opened by default. The "Subject type" select should be disabled and pre-selected by the subject type from the left-side. To proceed to the next input group, the user can click on "Next step", the opposite goes for "Back". When there is no input-group left, show a confirmation button "Create" button. We could display the upcoming property name after "New Property" as "New Property ${property.name}".

![Image](https://github.com/helpwave/web/assets/40192999/b03e3f8a-28a9-4b59-96fe-1424f0fbc6dc)

**Comment by DasProffi** [comment]
Done in https://github.com/helpwave/web/pull/931
