### ISSUE TITLE
Properties section on patient details

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#930]
To show the properties for a subject (patient), we need to implement the properties section on the patient details as designed. This section should list all properties for a subject in a paginated manner, the list for properties should be searchable as well. If the subject does not have properties assigned. The last row should display the "Add property" row as implemented in a follow-up issue.

The functionality for this list (including fetching of the properties by subject) could be implemented by a component. Please provide some example data for properties for the patient subject so we can review the this functionality.

https://github.com/helpwave/services/pull/619

![Image](https://github.com/helpwave/web/assets/40192999/1c810067-f9ae-4f0c-af71-00a3271a438b)

**Comment by DasProffi** [comment]
Done in #935
