### ISSUE TITLE
Date property without time

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#941]
### Describe the feature

The [existing date property](http://localhost:6006/?path=/story/user-action-property--date-property-variation) should also have the option to input/select date only (without the time). This could either a new property or a option on the existing one. I guess the first option would probably better suited for the composition of the properties.

### Why is this feature needed?

As an already discussed feature. services already implemented this type.

**Comment by DasProffi** [comment]
Done in #945
