### ISSUE TITLE
German translations

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#942]
### Describe the chore

Please translate the following pages from german to english

- https://helpwave.de/product/tasks
- https://helpwave.de/story

**Comment by MaxSchaefer** [comment]
@helpwave/medical

**Comment by yeahmoin** [comment]
**1. Das Problem erkennen**

helpwave entstand aus einem einfachen Problem: Wie können wir unser Wissen über Software und digitale Werkzeuge nutzen, um das Leben der Mitarbeiter im Gesundheitswesen zu erleichtern? Und woran mangelt es der aktuell im Gesundheitssystem genutzten Software?  In der unmittelbaren Arbeit für unsere Patient*innen erleben wir die Frustration veralteter, ineffizienter und nicht intuitiver Software tagtäglich! Die Folgen für uns und die Versorgung im Gesundheitssystem sehen wir in unserer täglichen Arbeit und. Der aber noch frustrierendere Teil: Krankenhäuser geben Millionen ihres Budgets für Tools aus, die ineffizient sind und uns das Leben schwer machen, anstatt es zu vereinfachen. Der weltweite Markt für Software-as-a-Service im Gesundheitswesen wird im Jahr 2022 auf rund 28 Milliarden US $ geschätzt, mit einem erwarteten Wachstum auf über 75 Milliarden USD allein in den nächsten zehn Jahren. Arbeitest du im Gesundheitswesen? Wann hattest du das letzte Mal das Gefühl, dass die Software, die du verwendest, Milliarden wert ist? Eben! helpwave will die Dinge anders angehen: Den Helden des Gesundheitswesens die Software zu liefern, die sie verdienen. Großartige Tools, die das Budget der Krankenhäuser nicht ausbluten lassen. Den Krankenhäusern die Kontrolle über ihre Infrastruktur und ihre Daten zurückgeben. Forschern den Zugang zu Daten ermöglichen, um die Patientenversorgung zu verbessern. Und das Wichtigste: Erleichterung des Lebens von Mitarbeitern im Gesundheitswesen.


**2. helpwave-tasks und das Open-Innovation-Konzept**

Begeistert von all den Menschen, die ihr Leben der Patientenversorgung widmen, wollten wir direkt in die erste Reihe gehen: Mit helpwave tasks haben wir ein Tool entwickelt, das den Mitarbeitenden im Gesundheitswesen das Leben leichter machen soll. Wir bringen moderne Konzepte des schlanken Projektmanagements in die Teams des Gesundheitswesens und ermöglichen es den Mitarbeitenden im Gesundheitswesen, eine Lücke zu füllen, die ihr derzeitiges Instrumentarium nicht abdeckt. Wir wollen sicherstellen, dass helpwave tasks nicht nur ein weiteres Tool ist, das im Gesundheitswesen verwendet wird, sondern ein Tool, das von den Menschen, die es verwenden, geliebt wird. Deshalb haben wir Designer, Entwickler und Visionäre mit den Menschen zusammengebracht, die es tagtäglich anwenden: Ärzt*innen, Pflegepersonal, Studierenden, Forschenden und Verwaltungsangestellte. Wir wollten ihnen ein Werkzeug an die Hand geben, mit dem sie ihre Arbeit besser organisieren, effizienter kommunizieren und einen besseren Überblick über ihre Aufgaben behalten können. Wir wollten ihnen ein Werkzeug an die Hand geben, das einfach zu bedienen ist, das intuitiv ist und einfach Spaß macht! Bei helpwave erfolgt die Softwareentwicklung nicht von oben nach unten. Die Mitarbeiter des Gesundheitswesens werden von Anfang an in die Diskussion einbezogen. Jeder Schritt wird von echten Mitarbeitern des Gesundheitswesens mit jahrelanger Erfahrung aus verschiedenen Bereichen überprüft. Funktionswünsche und Vorschläge kommen direkt aus den Stationen, Operationssälen und Forschungslabors unserer Community. helpwave ist ein Open Innovation und Open Source Unternehmen. Was heißt das genau?  Wir glauben, dass die besten Ideen von den Menschen kommen, die direkt von den Problemen betroffen sind, die wir zu lösen versuchen. Und wir glauben, dass in einem Gesundheitssystem, das auf der Idee des Wissens- und Erfahrungsaustauschs aufbaut, Software nicht anders sein sollte. Deshalb haben wir uns verpflichtet, nicht nur unser Wissen und unsere Erfahrung mit der Gemeinschaft zu teilen, sondern auch unseren gesamten Quellcode für alles, was wir entwickeln. Das macht den Entwicklungsprozess bei helpwave effizienter, sicherer, agiler und integrativer. Wir sind stolz darauf, sagen zu können, dass helpwave tasks ein Tool ist, das von Menschen im Gesundheitswesen für Menschen im Gesundheitswesen entwickelt wurde.


**3. Die Zukunft von helpwave**

Aufgrund unserer Erfahrung bei der Entwicklung von helpwave-tasks waren wir in der Lage, ein grundlegendes Problem auf dem Markt für Software im Gesundheitswesen zu erkennen: Der Einsatz von Software im Gesundheitswesen ist ein Albtraum. Die Realität: Die IT-Infrastruktur in Krankenhäusern ist oft unzuverlässig, veraltet und schlicht nicht sicher. Fehlende Interoperabilität fordert ihren Tribut von den Mitarbeitenden und macht die Wartung der Infrastruktur schwieriger als anderswo. Hohe regulatorische Anforderungen treiben den Preis in die Höhe und machen es kleinen Unternehmen schwer, in den Markt einzutreten. Und der Markt wird von einigen wenigen großen Akteuren beherrscht, die nicht daran interessiert sind, den Status quo zu ändern. Hier kommt helpwave ins Spiel: Wir entwickeln eine Plattform, die den Einsatz von Software im Gesundheitssystem erleichtern soll. Wir wollen den Krankenhäusern die Kontrolle über ihre Infrastruktur und ihre Daten zurückgeben. Durch den Einsatz von Spitzentechnologie wollen wir nicht nur die Grundlage für die Digitalisierung des Gesundheitsmarktes schaffen, sondern auch einen völlig neuen Zugang zum Markt für alle möglichen neuen Akteure eröffnen. Für uns ist das die wahre Bedeutung von Open Innovation. Wir laden alle ein, das Gesundheitssystem besser zu machen.

**Comment by yeahmoin** [comment]
**helpwave tasks**

Die erste Open-Source-Team-Management-Plattform für Mitarbeitende im Gesundheitswesen

helpwave tasks erhöht die Produktivität in deinem klinischen Team. Lass der ausgedruckten Stationsliste hinter dir und koordiniere deine Ihre Arbeit und die Arbeit deines Teams mit einer modernen Kanban-Schnittstelle. helpwave tasks wurden von modernen Branchenarbeitsabläufen und Best Practices aus dem Lean-Projektmanagement inspiriert und wendet sie auf die klinische Umgebung an.

**Aufgabenvorlagen**
Speichere sich wiederholende Aufgaben als Vorlagen. Standardisiere deine Arbeitsabläufe und teile sie mit deinem Team.

**Zusammenarbeiten**
Du und dein Team arbeiten synchronisiert.

**Patienten**
Moderne Dashboards für deine Patient*innen. Behalte den Überblick über den Fortschritt und deine Aufgaben.

**Du bist ein medical hero?**
helpwave tasks zielt darauf ab, bei der täglichen Arbeit zu helfen!
helpwave tasks ist eine moderne Kanban-Schnittstelle, die hilft, deine Arbeit und die Arbeit deines Teams zu koordinieren. Notiere dir deine Aufgaben für deinen Patienten für dich selbst und für dein Team. Standardisiere deine Workflows, indem du sie als Vorlage speicherst und mit deinen neuen Kollegen für ein einfaches Onboarding teilst. Erhalte Benachrichtigungen über bevorstehende Aufgaben und nutzen unsere verschiedenen Dashboards, um Patienten und Behandlungsverlaufe zu verfolgen. helpwave tasks ist die erste Open-Source-Teammanagement-Plattform für Mitarbeiter im Gesundheitswesen.

**Sie arbeiten in der Krankenhausverwaltung?**
Wie helpwave tasks Ihre Probleme lösen kann!
helpwave-Aufgaben wurden von modernen Branchenarbeitsabläufen und Best Practices aus dem Lean-Projektmanagement inspiriert und wenden sie auf das klinische Umfeld an. Die Verfolgung von Aufgaben und Arbeitsabläufen in einem klinischen Umfeld führt zu einer besseren Patientenversorgung und einer effizienteren Nutzung von Ressourcen. Hilfewellenaufgaben können die Zufriedenheit der Mitarbeiter und die Patientensicherheit erhöhen. Verwenden Sie es als sichere Grundlage für Ihre Abrechnungsprozesse.
