### ISSUE TITLE
Kanban component for tasks

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#96]
![Tasks Section](https://user-images.githubusercontent.com/40192999/226185273-15f4f242-1779-4784-b453-545fa2a85fdb.jpg)

This component should be an aggregate of many other components like `status pills`, `single task tile`, `kanban header` and also the `kanban columns`. It should be possible to pass an array of tasks to the component.

**Comment by DasProffi** [comment]
when should a progress indicator be shown? Only on selected or marked tasks, the design is clear here

**Comment by DasProffi** [comment]
Is the description of the middle single task tiles just "Doesn't have subtasks" or should the component check against that?

Also do we want to allow drag and dropping the single task tiles?

**Comment by MaxSchaefer** [comment]
> Is the description of the middle single task tiles just "Doesn't have subtasks" or should the component check against that?

It's just the description. 😀 

> Also do we want to allow drag and dropping the single task tiles?

Yes, drag an drop!

**Comment by use-to** [comment]
We should split this issues into smaller ones. I think a progreess-indicator for example could be a good standalone issue.
We should also track those atomic issues in this big one.
