### ISSUE TITLE
Badge with Image component

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#965]
This badge consists of an image and a text. The order can be [image, text] or [text, image]. The bade will be used in text-card and profile components. According to Storybook, we already have a chip component.

Also please checkout our Figma for the usage of this component.

![Image](https://github.com/helpwave/web/assets/40192999/2417e235-6269-4381-b58d-e349b28de1ee)

**Comment by DasProffi** [comment]
This component is very similar to the `Tile` component, as it uses a prefix and a title. I believe introducing a new component would not be beneficial, as the saved overhead is small.
