### ISSUE TITLE
Integrate `/placeholderbrand` page

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#974]
### Describe the feature

This page consists of many previously developed components, we now need to integrate them on one page. We will replace the example with real informations ones later on. Please take a look at our Figma, the trailing contact section can be ignored for now.

![Image](https://github.com/helpwave/web/assets/40192999/55866831-f9af-469b-ac62-90b5f0576ed8)

### Why is this feature needed?

The `/placeholderbrand` a new page our `landing-page` to communicate our one of our new projects. 

### **Until publicly announced, we will not disclose any informations about this project and are using example data.**

**Comment by DasProffi** [comment]
Done in https://github.com/helpwave/web/issues/980
