### ISSUE TITLE
`/mediquu` responsive mobile-layout

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#983]
### Describe the feature

With some styling adjustments, we can adopt the mobile-layout for this page
![helpwave x mediQuu](https://github.com/helpwave/web/assets/40192999/16d5b315-ce8c-444b-8342-6644b60e1754)

### Why is this feature needed?

To increase the usability on mobile

**Comment by DasProffi** [comment]
Implanted on main and will also be addressed in #982
