### ISSUE TITLE
Generic two-columns-center-seperator view

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#99]
We have an large amount of create/update/detail screens that are in an two-column layout. On the left site, we have a listing of  entities of the same kind, the last tile should be always a create entity tile. The right site is the detail view. When the user selects an entity from the left site, the right site gets updated by with the values from this entity. Most of the time, the navigation between these entites can be generic. I've attached some screenshots to implement the generic behaviour against.

The concrete implementation of these screens (for org, wards, task templates) are tracked in another issue.

![Tasks - overview of organizations](https://user-images.githubusercontent.com/40192999/226186093-a7b2f74b-2d77-44ba-be97-c4f8d612ac87.jpg)
![Tasks - overview of wards in an organization](https://user-images.githubusercontent.com/40192999/226186097-86c0fc84-4b66-4c68-afaa-19dfa96b950a.jpg)
![Tasks - overview of template tasks](https://user-images.githubusercontent.com/40192999/226186100-5a06c941-7933-4ded-9caf-cbc2763ba3e5.jpg)

**Comment by DasProffi** [comment]
What should the scroll behavior look like on overflow, two independent columns?

Is the header/navigationbar floating above this component or is there another component in which the header and current page are simultaniously inserted?

**Comment by MaxSchaefer** [comment]
> What should the scroll behavior look like on overflow, two independent columns?
> 
> 
> 
> Is the header/navigationbar floating above this component or is there another component in which the header and current page are simultaniously inserted? Maybe should the header be reused on every page?

- Scroll behavior: Two years independent columns
- The breadcrumb menu is not in the responsibility of this generic component. But the header title is.

**Comment by MaxSchaefer** [comment]
@DasProffi and I have been discussing a state store in the context of this issue. With the implementation of this view, we need to pass some state up and down the component structure.

IMO, we have three options:
- Passing state up and down via props
- Use of a full-fledged state management
- Development of a simple state management solution mostly based on `useContext `

I like `useConext` a lot, and it should be possible to implement something like a local/regional state management for just a component or a view and their corresponding child-components. [Take a look at my rough `useContext` example](https://github.com/helpwave/web/commit/a9be3e12ad9d738c050dc3be955fa24c90ddeb06) 😄 

@JannikWibker what do you think?

**Comment by DasProffi** [comment]
- two column layouting component, right and left (component or something else)
- wrapper arround two column layput for each page
	- wrapper saves the state of both sides
	
e.g organisation page
- query to fetch organizations
- state for currently selected
- mutation function for updates given as a callback for lower level components
- opimistic updates of the page state then validation
- react hook to invalidate component states
- different mutators for create, delete, update
=> query and state are handled on the page level

Therefore the two column layout is only to layout and wont have any state handling function
