### ISSUE TITLE
Horizontal gallery

### ISSUE THREAD

**Issue by MaxSchaefer** [helpwave/web#996]
### Describe the feature

- Develop a horizontal gallery, with focus on the underlaying structure. You can use the example data of Figma for the content.
- The content of the gallery can be quite generic, but for now, we have these cards inside of a the gallery. Should these cards be gallery specific?
- With mouse-drag, the gallery can be moved.
- On-Click on the pill, should change/move the gallery too.
- Auto-rotate by time

![Section 4](https://github.com/helpwave/web/assets/40192999/b002ed40-357b-4629-afbc-9d3ec282221e)
![Partners](https://github.com/helpwave/web/assets/40192999/e9901fb6-6177-4e66-aeac-934614694bd3)

### Why is this feature needed?

New landing-page :)

**Comment by MaxSchaefer** [comment]
Blocked by https://github.com/helpwave/web/issues/997

**Comment by DasProffi** [comment]
Implemented on main
